id: A48BF7DE6
title: A Brief Daily Practice of Damdrip Nyepa Kunsel
type: translation
source_metadata:
  languages:
  - en
  - bo
  datatype: PlainText
  created_at: 2022-03-01 01:53:59.494026
  last_modified_at: 2022-03-01 01:53:59.494034
