id: A48BF7DE6
title: Prayer of the View, Meditation and Conduct
type: translation
source_metadata:
  languages:
  - en
  - bo
  datatype: PlainText
  created_at: 2022-03-01 01:53:59.526643
  last_modified_at: 2022-03-01 01:53:59.526645
