id: A48BF7DE6
title: Profound Prayer of Aspiration
type: translation
source_metadata:
  languages:
  - en
  - bo
  datatype: PlainText
  created_at: 2022-03-01 01:53:59.527690
  last_modified_at: 2022-03-01 01:53:59.527693
