id: A48BF7DE6
title: 'Granting the Wish for Immortality: A Prayer for the Long Life of Dzarong Trulshik
  Rinpoche, the Representative of Guru Rinpoche'
type: translation
source_metadata:
  languages:
  - en
  - bo
  datatype: PlainText
  created_at: 2022-03-01 01:53:59.508331
  last_modified_at: 2022-03-01 01:53:59.508333
