id: A48BF7DE6
title: Prayer for the Long Life of Sogyal Rinpoche—chimé kunnyé
type: translation
source_metadata:
  languages:
  - en
  - es
  - fr
  - bo
  datatype: PlainText
  created_at: 2022-03-01 01:53:59.520671
  last_modified_at: 2022-03-01 01:53:59.520676
