id: A48BF7DE6
title: Prayer for the Long Life of Taklung Tsetrul Rinpoche
type: translation
source_metadata:
  languages:
  - en
  - bo
  datatype: PlainText
  created_at: 2022-03-01 01:53:59.523131
  last_modified_at: 2022-03-01 01:53:59.523134
