id: A48BF7DE6
title: Verses of Homage to the Buddhas and Bodhisattvas Together with their Mantras
type: translation
source_metadata:
  languages:
  - en
  - de
  - bo
  datatype: PlainText
  created_at: 2022-03-01 01:53:59.536327
  last_modified_at: 2022-03-01 01:53:59.536330
