id: A48BF7DE6
title: Long Life Prayer for Kyabje Dzarong Trulshik Rinpoche
type: translation
source_metadata:
  languages:
  - en
  - bo
  datatype: PlainText
  created_at: 2022-03-01 01:53:59.510874
  last_modified_at: 2022-03-01 01:53:59.510877
