id: A48BF7DE6
title: 'The Quintessential Blessing: A Guru Yoga'
type: translation
source_metadata:
  languages:
  - en
  - bo
  datatype: PlainText
  created_at: 2022-03-01 01:53:59.532665
  last_modified_at: 2022-03-01 01:53:59.532667
