id: A48BF7DE6
title: Long Life Prayer for Mayum Tsering Wangmo
type: translation
source_metadata:
  languages:
  - en
  - de
  - es
  - fr
  - bo
  datatype: PlainText
  created_at: 2022-03-01 01:53:59.514085
  last_modified_at: 2022-03-01 01:53:59.514088
