id: A48BF7DE6
title: Prayer for the Long Life of Dilgo Khyentsé II of Shechen, Urgyen Tenzin Jigme
  Lhundrup
type: translation
source_metadata:
  languages:
  - en
  - de
  - es
  - fr
  - it
  - nl
  - bo
  datatype: PlainText
  created_at: 2022-03-01 01:53:59.517107
  last_modified_at: 2022-03-01 01:53:59.517110
