id: A48BF7DE6
title: Prayer for the Long Life of Chökyi Nyima Rinpoche
type: translation
source_metadata:
  languages:
  - en
  - bo
  datatype: PlainText
  created_at: 2022-03-01 01:53:59.515166
  last_modified_at: 2022-03-01 01:53:59.515169
