id: A48BF7DE6
title: The Attainment of Immortality
type: translation
source_metadata:
  languages:
  - en
  - de
  - es
  - fr
  - bo
  datatype: PlainText
  created_at: 2022-03-01 01:53:59.531217
  last_modified_at: 2022-03-01 01:53:59.531220
